import type { Metadata } from "next";
import { Geist, Geist_Mono, Raleway } from "next/font/google";

import "./globals.css";
import { TabProvider } from "@/context/TabContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const raleway = Raleway({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
  variable: '--font-raleway',
  display: 'swap',
});

export const metadata: Metadata = {
  title: "LumaShape",
  description: "Generated by create next app",
  icons:{
    icon: "/images/icons/lumashape.svg"
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${raleway.variable}  antialiased`}
      >
      {children}
      </body>
    </html>
  );
}
